# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.lineEdit_input = QtWidgets.QLineEdit(Form)
        self.lineEdit_input.setGeometry(QtCore.QRect(20, 80, 501, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.lineEdit_input.setFont(font)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.textEdit_result = QtWidgets.QTextEdit(Form)
        self.textEdit_result.setEnabled(True)
        self.textEdit_result.setGeometry(QtCore.QRect(20, 150, 661, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_result.sizePolicy().hasHeightForWidth())
        self.textEdit_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.textEdit_result.setFont(font)
        self.textEdit_result.setReadOnly(True)
        self.textEdit_result.setObjectName("textEdit_result")
        self.pushButton_trans = QtWidgets.QPushButton(Form)
        self.pushButton_trans.setGeometry(QtCore.QRect(540, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.pushButton_trans.setFont(font)
        self.pushButton_trans.setObjectName("pushButton_trans")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_theme = QtWidgets.QPushButton(Form)
        self.pushButton_theme.setGeometry(QtCore.QRect(614, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.pushButton_theme.setFont(font)
        self.pushButton_theme.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_theme.setCheckable(True)
        self.pushButton_theme.setChecked(False)
        self.pushButton_theme.setFlat(False)
        self.pushButton_theme.setObjectName("pushButton_theme")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_trans.setText(_translate("Form", "翻译"))
        self.comboBox.setItemText(0, _translate("Form", "必应翻译"))
        self.comboBox.setItemText(1, _translate("Form", "机器翻译"))
        self.pushButton_theme.setText(_translate("Form", "深色"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
